<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="UTF-8">
    <title>Single Page Web Applications with AngularJS by robertosequeira</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="stylesheets/normalize.css" media="screen">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/github-light.css" media="screen">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">Single Page Web Applications with AngularJS</h1>
      <h2 class="project-tagline"></h2>
      <a href="https://github.com/robertosequeira/coursera-spa-angular" class="btn">View on GitHub</a>
    </section>

    <section class="main-content">
      <h3><a id="welcome" class="anchor" href="#welcome" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Welcome</h3>

      <ol>
        <li><a href="module-1-assignment/">Module 1 - Assignment</a></li>
        <li><a href="module-2-assignment/">Module 2 - Assignment</a></li>
        <li><a href="module-3-assignment/">Module 3 - Assignment</a></li>
        <li><a href="module-4-assignment/">Module 4 - Assignment</a></li>
        <li><a href="module-5-assignment/">Module 5 - Assignment</a></li>
      </ol>

      <footer class="site-footer">
        <span class="site-footer-owner"><a href="https://github.com/robertosequeira/coursera-spa-angular">Single Page Web Applications with AngularJS</a> is maintained by <a href="https://github.com/robertosequeira">robertosequeira</a>.</span>

        <span class="site-footer-credits">This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the <a href="https://github.com/jasonlong/cayman-theme">Cayman theme</a> by <a href="https://twitter.com/jasonlong">Jason Long</a>.</span>
      </footer>

    </section>
  </body>
</html>
